
version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: goal_tracker
      POSTGRES_USER: goal_tracker_user
      POSTGRES_PASSWORD: goal_tracker_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

